package com.interstellar.rahulpihujetpackdemo

/*
Splash (2s) → Welcome → Login/Register → Home (Bottom Nav)
├── Home Tab → Products → Product Detail
├── Wishlist Tab → Wishlist Detail
├── Cart Tab → Cart Detail
└── Profile Tab → Profile Detail → Logout



📁 Final File Structure:
├── MainActivity.kt ✅
├── RootNavGraph.kt ✅
├── AuthManager.kt ✅
├── GlobalNavigationActions.kt ✅
├── LocalNavController.kt ✅
├── authGraph.kt ✅
├── homeGraph.kt ✅
├── NavigationAnimations.kt ✅
└── All Screen Composables ✅


 */